seed: 42
data_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
logs_dir: logs_dl
datasets:
  - name: Taxonomy_Phylum
    task: multilabel
pre-transforms:
  LaplacianPE:
    dim: 20
  RandomWalkPE:
    dim: 20
model:
  - name: gifflar
    hidden_dim: 1024
    batch_size: 256
    num_layers: 8
    epochs: 1
    learning_rate: 0.001
    optimizer: Adam
    suffix: _1024_8
