seed: 42
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data_final
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs_final
datasets:
  - name: Tissue
    task: multilabel
pre-transforms:
  GIFFLARTransform:
  GNNGLYTransform:
  ECFPTransform:
  SweetNetTransform:
  RGCNTransform:
  RandomWalkPE:
    dim: 20
    individual: False
  LaplacianPE:
    dim: 20
    individual: False
model:
  - name: svm
    random_state: 42
