seed: 1234
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data_final
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs_final
datasets:
  - name: Glycosylation
    task: classification
pre-transforms:
  GIFFLARTransform:
  GNNGLYTransform:
  ECFPTransform:
  SweetNetTransform:
  RGCNTransform:
  RandomWalkPE:
    dim: 20
    individual: False
  LaplacianPE:
    dim: 20
    individual: False
model:
  - name: gnngly
    feat_dim: 128
    hidden_dim: 1024
    batch_size: 512
    num_layers: 8
    epochs: 100
    patience: 30
    learning_rate: 0.001
    optimizer: Adam
    suffix:
