seed: 42
data_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
logs_dir: logs
datasets:
  - name: Taxonomy_Domain
    task: multilabel
pre-transforms:
model:
  - name: gnngly
    hidden_dim: 1024
    batch_size: 512
    num_layers: 5
    epochs: 1
    patience: 30
    learning_rate: 0.001
    optimizer: Adam
