seed: 42
data_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
datasets:
  # - name: Immunogenicity
  #   task: classification
  # - name: Glycosylation
  #   task: classification
  # - name: Taxonomy_Domain
  #   task: multilabel
  - name: Taxonomy_Kingdom
    task: multilabel
  # - name: Taxonomy_Phylum
  #   task: multilabel
  # - name: Taxonomy_Class
  #   task: multilabel
  # - name: Taxonomy_Order
  #   task: multilabel
  - name: Taxonomy_Family
    task: multilabel
  - name: Taxonomy_Genus
    task: multilabel
  - name: Taxonomy_Species
    task: multilabel
pre-transforms:
model:
  - name: gnngly
    hidden_dim: 14
    batch_size: 256
    num_layers: 5
    epochs: 200
    patience: 30
    learning_rate: 0
    optimizer: Adam

