seed: 42
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs
datasets:
  # - name: Immunogenicity
  #   task: classification
  # - name: Glycosylation
  #   task: classification
  # - name: Tissue
  #   task: multilabel
  - name: Taxonomy_Domain
    task: multilabel
model:
  - name: glylm
    pre_tokenizer: char
    token_file: none
    model_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/none_char_0_t6/checkpoint-5922440
    hidden_dim: 320
    epochs: 100
    learning_rate: 0.001
    batch_size: 128
    optimizer: Adam
    suffix: _none_char_t6_20
