seed: 42
data_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data_embed
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs_embed
datasets:
  - name: Immunogenicity
    task: classification
  - name: Glycosylation
    task: classification
  - name: Taxonomy_Domain
    task: multilabel
  - name: Taxonomy_Kingdom
    task: multilabel
  - name: Taxonomy_Phylum
    task: multilabel
  - name: Taxonomy_Class
    task: multilabel
  - name: Taxonomy_Order
    task: multilabel
  - name: Taxonomy_Family
    task: multilabel
  - name: Taxonomy_Genus
    task: multilabel
  - name: Taxonomy_Species
    task: multilabel
pre-transforms:
  PretrainEmbed:
    folder: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data_embed/
    model_name: GIFFLAR
    hash_str: 659a0fbd
    pooling: global_mean
model:
  - name: mlp
    feat_dim: 1024
    hidden_dim: 1024
    batch_size: 256
    num_layers: 3
    epochs: 100
    patience: 30
    learning_rate: 0
    optimizer: Adam
    suffix: _pre_exp
