seed: 42
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs_spec
datasets:
  - name: Spectrum
    task: spectrum
pre-transforms:
  GIFFLARTransform:
  GNNGLYTransform:
  ECFPTransform:
  SweetNetTransform:
  RGCNTransform:
model:
  - name: mlp
    feat_dim: 1024
    hidden_dim: 1024
    batch_size: 16
    num_layers: 3
    epochs: 100
    patience: 30
    learning_rate: 0.001
    optimizer: Adam
  - name: gifflar
    feat_dim: 128
    hidden_dim: 1024
    batch_size: 16
    num_layers: 8
    epochs: 100
    learning_rate: 0.001
    optimizer: Adam
    pooling: global_mean
    suffix: _128_8_gp
