seed: 42
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs_test
datasets:
  - name: Glycosylation
    task: classification
pre-transforms:
  GIFFLARTransform:
  GNNGLYTransform:
  ECFPTransform:
  SweetNetTransform:
  RGCNTransform:
model:
  - name: mlp
    feat_dim: 1024
    hidden_dim: 1024
    batch_size: 16
    num_layers: 3
    epochs: 100
    patience: 30
    learning_rate: 0.001
    optimizer: Adam
