seed: 42
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/logs
datasets:
  - name: Immunogenicity
    task: classification
  - name: Glycosylation
    task: classification
  - name: Tissue
    task: multilabel
  - name: Taxonomy_Domain
    task: multilabel
model:
  - name: glylm
    token_file: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/bpe_lib_2500.pkl
    model_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/bpe_lib_2500_t6/checkpoint-5927260
    hidden_dim: 320
    epochs: 100
    learning_rate: 0.001
    batch_size: 256
    optimizer: Adam
    suffix: _bpe_lib_25_t6_20
  - name: glylm
    token_file: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/wp_lib_5000_t6.pkl
    model_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/wp_lib_5000_t6/checkpoint-5927260
    hidden_dim: 320
    epochs: 100
    learning_rate: 0.001
    batch_size: 256
    optimizer: Adam
    suffix: _wp_lib_50_t6_20
