seed: 42
#root_dir: /home/daniel/Data1/roman/GIFFLAR/lgi_data
#logs_dir: /home/daniel/Data1/roman/GIFFLAR/lgi_logs
#origin: /home/daniel/Desktop/GIFFLAR/lgi_data_full.pkl
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/lgi_data
logs_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/lgi_logs
origin: /home/rjo21/Desktop/GIFFLAR/lgi_data_20.pkl
add_valid:
  - name: UniLectin
    path: /home/rjo21/Desktop/GIFFLAR/experiments/results/unilectin.tsv
    task: classification
model:
  glycan_encoder:
    name: gifflar
    feat_dim: 128
    hidden_dim: 1024
    num_layers: 8
    pooling: global_mean
  lectin_encoder:
    name: ESM
    layer_num: 33
  batch_size: 256
  epochs: 10
  learning_rate: 0.001
  optimizer: Adam

