seed: 42
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/
corpus_file: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/glycoverse_2371k.txt
max_length: 200
tokenizations:
  - name: WP_Lib_5000_t6
    pretokenizer: lib
    tokenizer: wp
    token_file: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/wordpiece_lib_5000.pkl
  - name: WP_Lib_7500_t6
    pretokenizer: lib
    tokenizer: wp
    token_file: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/wordpiece_lib_7500.pkl
  - name: WP_Lib_10000_t6
    pretokenizer: lib
    tokenizer: wp
    token_file: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/unique/GlyLM/wordpiece_lib_10000.pkl
model:
  epochs: 20
  batch_size: 8
  num_layers: 6
  hidden_size: 320
  num_heads: 20
