name: # Name of the dataset
data_dir: # Path to the dataset
featurization:
  atoms: # List from ...
  bonds: # List from ...
  monosacchs: # List from
training:
  batch_size: # Batch size
  epochs: # Number of epochs
  learning_rate: # Learning rate
  optimizer: # Optimizer
