seed: 42
data_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
datasets:
  - name: Taxonomy_Phylum
    task: multilabel
pre-transforms:
model:
  - name: rf
    n_estimators: 500
    n_jobs: -1
    random_state: 42
  - name: svm
    random_state: 42
  - name: xgb
    random_state: 42
