seed: 42
data_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/
root_dir: /scratch/SCRATCH_SAS/roman/Gothenburg/GIFFLAR/data
datasets:
  - name: class-1
    label: class
    task: classification
pre-transforms:
model:
  - name: rf
    n_estimators: 500
    n_jobs: -1
    random_state: 42
  - name: mlp
    hidden_dim: 1024
    batch_size: 256
    num_layers: 3
    epochs: 100
    patience: 30
    learning_rate: 0
    optimizer: Adam
  - name: sweetnet
    hidden_dim: 128
    batch_size: 256
    epochs: 50
    patience: 30
    learning_rate: 0.001
    optimizer: Adam
  - name: gnngly
    hidden_dim: 14
    batch_size: 256
    num_layers: 5
    epochs: 200
    patience: 30
    learning_rate: 0
    optimizer: Adam
  - name: gifflar
    hidden_dim: 128
    batch_size: 32
    num_layers: 3
    epochs: 100
    learning_rate: 0.001
    optimizer: Adam
