dataset-name: Taxonomy_Subdomain
seed: 42
data_dir: ./
root_dir: ./data
featurization:
  - name: clean
  - name: scalar
    level: atoms
    embed_dim: 128
    index: 0
    mode: random
  - name: scalar
    level: bonds
    embed_dim: 128
    index: 0
    mode: random
  - name: scalar
    level: monosacchs
    embed_dim: 128
    index: 0
    mode: random
model:
  hidden_dim: 128
  batch_size: 32
  num_layers: 3
  epochs: 100
  learning_rate: 0.001
  optimizer: Adam
