dataset-name: Taxonomy_Subdomain
seed: 42
data_dir: ./
root_dir: ./data
featurization:
  - name: mlp
model:
  name: mlp
  hidden_dim: 1024
  batch_size: 256
  num_layers: 3
  epochs: 100
  patience: 30
  learning_rate: 0
  optimizer: Adam
