seed: 42
data_dir: ./
root_dir: ./data
dataset-name:
  - Immunogenicity
  - Glycosylation
model:
  - name: rf
    n_estimators: 500
    n_jobs: -1
    random_state: 42
    featurization:
      - name: mlp
  - name: svm
    dual: auto
    random_state: 42
    featurization:
      - name: mlp