dataset-name: Taxonomy_Subdomain
seed: 42
data_dir: ./
root_dir: ./data
model:
  name: sweetnet
  hidden_dim: 128
  batch_size: 256
  epochs: 50
  patience: 30
  learning_rate: 0.001
  optimizer: Adam
  featurization:
    - name: sweetnet
